# Generated by Django 5.0.1 on 2024-01-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_gympaln_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('conatct', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('weight', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='memeber',
            name='phonenumber',
            field=models.CharField(max_length=12),
        ),
    ]
