# Generated by Django 5.0.1 on 2024-01-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_enquries_equipments_alter_memeber_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquries',
            name='description',
            field=models.CharField(default='Not solve', max_length=500),
        ),
        migrations.AddField(
            model_name='equipments',
            name='image',
            field=models.ImageField(default='equipments2', upload_to='static/images/'),
        ),
    ]
